### ISSUE TITLE
Issue with Xml serialization 

### ISSUE THREAD

**Issue by girishchandranc** [girishchandranc/autosarfactory#14]
The xml elements are created on the fly whenever the api's are used and this isn't ideal and could lead to schema violations. This needs a rework on the way xml is serialized.

**Comment by girishchandranc** [comment]
Development ongoing in the branch 14-issue-with-xml-serialization.

**Comment by girishchandranc** [comment]
Hi @christianhecht86 ,
Could you please check and review the changes? Meanwhile, I will also try adding in some py tests for the fix.

Thanks!

**Comment by girishchandranc** [comment]
Hi @christianhecht86 ,
I fixed the issues reported by you. Have also added a couple of unit tests. Could you please check and review?
Thanks :)

**Comment by christianhecht86** [comment]
Hi @girishchandranc ,

unfortunately it solves not the entire issue. Please see my email.

Christian

**Comment by girishchandranc** [comment]
Hi @christianhecht86 ,
Fixed the issue reported you via email. Can you check it again and let me know if that works for you. 
Thanks again,
Girish

**Comment by christianhecht86** [comment]
Hi @girishchandranc ,

now it looks much better. Only two things...

1) Schema error in CanNetwork.arxml	Line 62 Column 50: Element '{http://autosar.org/schema/r4.0}CONTEXT-COMPONENT-REFS': This element is not expected. Expected is one of ( {http://autosar.org/schema/r4.0}CONTEXT-COMPONENT-REF, {http://autosar.org/schema/r4.0}TARGET-COMPONENT-REF ).

2) different ordering of CONTEXT-COMPONENT-REF

code:
swcMap1.set_contextComposition(rootComp)
swcMap1.add_contextComponent(asw1_proto)
swcMap1.add_contextComponent(asw2_proto)

ARXML:
                          <CONTEXT-COMPONENT-REFS>
                            <CONTEXT-COMPONENT-REF DEST="SW-COMPONENT-PROTOTYPE">/Swcs/Comp/asw2_proto</CONTEXT-COMPONENT-REF>
                            <CONTEXT-COMPONENT-REF DEST="SW-COMPONENT-PROTOTYPE">/Swcs/Comp/asw1_proto</CONTEXT-COMPONENT-REF>
                          </CONTEXT-COMPONENT-REFS>

For some Lists, there should be a tagged value isOrdered="true" in the ecore definition. Here it is important to keep the ordering.


Christian

**Comment by girishchandranc** [comment]
Hi @christianhecht86 ,
Was able to fix the mentioned issues as well :) Basically, the tool wasn't properly handling the element of type "roleTypeWrapper". 

Can you please check together with the issues you reported via email to see it the latest commit satisfies all the issues reported.

**Comment by christianhecht86** [comment]
Hi @girishchandranc ,

thank you for your hard work to fix the serialization issues. In current version my reported issues are solved.

So, from my point of view, you should merge it to master branch.

Christian
