### ISSUE TITLE
Issue with identifying which element a value belongs in the GUI

### ISSUE THREAD

**Issue by AD1D1** [girishchandranc/autosarfactory#15]
Hi @girishchandranc ,

Thanks again for your support on the previous issues,

I am just facing another issue, when I read in the files and try to visualise the tree using the GUI, 

I am trying to visualize the numerical values in the arxml files, this shows up in the GUI tree as a NumercicalValueVariation Poiint and then on cicking that shows the properties and the Value for that path,

This is the problem I'm facing:

How do I understand as to which element the value belongs under? 

For example in the below structure, under Elekemnt1a SHORT-NAME, there are two different paths, first one ending with ID1 and the second ending with ID2 with two different values 0,1 (its different here but some cases values are same too!) but these are not shown in the GUI, it just shows parameterValues_@1 and below that NumercialValueVariationPoint and then it shows the value, similarly for the next one parameterValues_@2 and below that NumercialValueVariationPoint and then it shows the value - but it doesnt mention where this value comes from or where it belongs even in the Type column (which should show the Path) on the right in the GUI,

Could you please suggest a solution for this?

Thanks

![GitHub doubt](https://github.com/girishchandranc/autosarfactory/assets/66953528/73656567-65bc-422f-a7be-a373204b1b52)

**Comment by girishchandranc** [comment]
Hi @AD1D1 ,
Thanks for your question.
Please note that the viewer is very generic in nature and whenever it finds an element which is not Referrable(means without short-name), it tries to add some unique identifier to it. 
In your example, it seems like you are trying to view contents of a EcuC configuration values from a module description. TBH, if you also provide the definition file of the module description, you will find the parameter name in the "Definition" column of the properties view. 

In case, if you wish have a viewer which shows the parameter name in the tree viewer, then I suggest that you can use the autosarfactory framework and build up a module configuration viewer where you can show the parameter name taken from it's corresponding definition node.
Hope this helps!

**Comment by girishchandranc** [comment]
Closing issue as no feedback yet.
