### ISSUE TITLE
SHORT-NAME creation

### ISSUE THREAD

**Issue by qCyb3r** [girishchandranc/autosarfactory#16]
Hello,

I would like to address the following problem:

When creating a new EcucNumericalParamValue, I want to add a short name.
Currently however when running the function "new_EcucNumericalParamValue()" from the class "EcucContainerValue", it does only create the yellow marked output, without a SHORT-NAME node.
![image](https://github.com/girishchandranc/autosarfactory/assets/54896984/8b037140-c906-4866-b16f-0da9a33888e9)
By default I would expect a SHORT-NAME to be created if I enter a value inside "new_EcucNumericalParamValue(value)".
Is there a way to add a short name to this EcucNumericalParamValue like in the other ECUC-NUMERICAL-PARAM-VALUE?

**Comment by girishchandranc** [comment]
Hi @qCyb3r ,
First of all, sorry for the late response. 

The EcucParameterValue doesn't have short-name property according to Arxml schema and hence you can't set the short-name using the autosarfactory. 
Infact, you can set the definition node to a EcucParameterValue which has the actual short-name tag configured. It's the DEFINITION-REF tag in your arxml snippet.

**Comment by qCyb3r** [comment]
Thank you @girishchandranc .
Can you perhaps provide a hint how a call to create a DEFINITION-REF as shown above with a "DEST" (Destination) would look like?

**Comment by girishchandranc** [comment]
Sure, please checkout the method EcucParameterValue.set_definition.

**Comment by girishchandranc** [comment]
Closing as no feedback yet.
