### ISSUE TITLE
Issue while parsing arxml with schema 00048

### ISSUE THREAD

**Issue by Avya2023** [girishchandranc/autosarfactory#18]
I have tried parsing arxml with schema 00048, using the autosarfactory library. But I was facing KeyError while reading the file.               The error is due to unavailability of few nodes in autosarfactory library:
TRANSFORMATION-PROPS-TO-SERVICE-INTERFACE-ELEMENT-MAPPING-SET
SECURE-COM-PROPS-SET
STARTUP-CONFIG-SET
PROCESS-DESIGN-TO-MACHINE-DESIGN-MAPPING-SET
Is there any latest version of autosarfactory available to solve this issue?

**Comment by girishchandranc** [comment]
Hi, the autosarfactory is based on schema 00051 and the reported xml tags are removed since the 00050. And hence, there isn't a way for autosarfactory to read those elements. I can try generating a autosarfactory for the version 00048 if that helps you by any chance?
Thanks!

**Comment by girishchandranc** [comment]
Hi, I have attached the autosarfactory corresponding to 00048. Please let me know if this solves your issue.
JFYI, we have a plan to support multiple autosar versions in near future. Thank you!
[autosarfactory.zip](https://github.com/girishchandranc/autosarfactory/files/13190703/autosarfactory.zip)

**Comment by Avya2023** [comment]
Thankyou
Regards
Avya Kaila
________________________________
