### ISSUE TITLE
Export Ar-Package support

### ISSUE THREAD

**Issue by punithspal** [girishchandranc/autosarfactory#19]
Export a particular Ar-package maintaining its tree structure along with the parent packages in to a new arxml file.
The exported arxml shall be importable in tools like Matlab/Simulink/TargetLink

**Comment by girishchandranc** [comment]
Hi @punithspal ,
Thanks for the CR and I think, it really makes sense to have this feature in place. I think, it will be better if we could do it for all packageableElements. So, basically, ArPackage as well as any elements which comes directly under ArPackage. What do you think?

Thanks!

**Comment by punithspal** [comment]
> Hi @punithspal , Thanks for the CR and I think, it really makes sense to have this feature in place. I think, it will be better if we could do it for all packageableElements. So, basically, ArPackage as well as any elements which comes directly under ArPackage. What do you think?
> 
> Thanks!

Hello Girish,

That totally makes sense.
I would go ahead and extend it to all the AUTOSAR elements too.
For example, if I want to export a S/R interface and import it in another tool.
In Simulink, sometimes only the dictionary(datatypes and mappings) needs to be imported. 
I don't know if this is feasible, but it is definitely helpful.

**Comment by girishchandranc** [comment]
Hi @punithspal ,
I added the support for exporting the collectableElements(which means Ar-package as well as all packageableElements which includes ApplicationSwComponentType, SR interface, Signals etc etc). The changes are pushed to the branch https://github.com/girishchandranc/autosarfactory/tree/14-issue-with-xml-serialization. 

Following are the way to use it:
- option1(using export function available in the node itself)
```python
swc = autosarfactory.get_node('/Swcs/swc1')
swc.export_to_file('swc1Export.arxml', overWrite = True)
```
- option2(using export function where you pass the node)
```python
swc = autosarfactory.get_node('/Swcs/swc1')
autosarfactory.export_to_file(swc, 'swc1Export.arxml', overWrite = True)
```
Could you please check and let me know if this works for you?

**Comment by girishchandranc** [comment]
@punithspal  further regarding question on importing the the dictionary(datatypes and mappings). I believe they are all packageableElements. for eg: ImplementationDataTypes, ApplciationDataTypes, DataTypeMappingSet etc etc. Can you please check once and let me know if that works for you. I have described the usage in my previous comment. 
Thanks again!

**Comment by punithspal** [comment]
The issue is successfully implemented.
