### ISSUE TITLE
ARXML checker/checking

### ISSUE THREAD

**Issue by nithinvelupur** [girishchandranc/autosarfactory#25]
Is there any checking/validation that is done during export or import of ARXML? I am looking to create DEXT ARXML file and would like to ensure that the files i create are in-line with the AUTOSAR DEXT specification document.

PS: Sorry to highlight this as an issue. Didn't find the 'discussions' option for this repo.

**Comment by girishchandranc** [comment]
@nithinvelupur Currently, there is no explicit schema validation done. But, the model is 1:1 representation of the schema and hence if required, you could validate the output arxml file against the required schema. 

I know people are using autosarfactory to create the DEXT extract and so it works for the people.

**Comment by nithinvelupur** [comment]
> @nithinvelupur Currently, there is no explicit schema validation done. But, the model is 1:1 representation of the schema and hence if required, you could validate the output arxml file against the required schema.
> 
> I know people are using autosarfactory to create the DEXT extract and so it works for the people.

______
Thanks. Will post an issue, IF any.

**Comment by girishchandranc** [comment]
@nithinvelupur  sure.. Hope this tool helps you. Please feel free to post issue if you find. Thanks!

**Comment by nithinvelupur** [comment]
NP. I am currently unable to find any 'check' rules for such ARXML schema validation. Do you know where exactly I can get that?
I will try to contribute to your repo with possibly a checker module.

If that's OK with you.
